package git

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing"
	"github.com/go-git/go-git/v5/plumbing/object"
	githttp "github.com/go-git/go-git/v5/plumbing/transport/http"
	appconfig "forge-engine/internal/config"
	"forge-engine/pkg/logger"
	"go.uber.org/zap"
)

type Manager struct {
	config *appconfig.GitConfig
	auth   *githttp.BasicAuth
}

type Repository struct {
	URL      string
	LocalDir string
	repo     *git.Repository
}

func NewManager(cfg *appconfig.GitConfig) *Manager {
	auth := &githttp.BasicAuth{
		Username: cfg.Username,
		Password: cfg.Token,
	}

	return &Manager{
		config: cfg,
		auth:   auth,
	}
}

func (m *Manager) CreateRepository(ctx context.Context, appName string, files map[string]string) (*Repository, error) {
	gitLogger := logger.Logger.With(zap.String("component", "git_manager"), zap.String("app_name", appName))
	
	// Create repository name (sanitized)
	repoName := m.sanitizeRepoName(appName)
	repoURL := fmt.Sprintf("%s/%s/%s", m.config.BaseURL, m.config.Organization, repoName)
	
	// Create local directory
	localDir := filepath.Join("/tmp", "forge-repos", repoName)
	if err := os.RemoveAll(localDir); err != nil {
		return nil, fmt.Errorf("failed to clean local directory: %w", err)
	}
	
	if err := os.MkdirAll(localDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create local directory: %w", err)
	}

	gitLogger.Info("Creating Git repository", zap.String("repo_url", repoURL), zap.String("local_dir", localDir))

	// Initialize repository
	repo, err := git.PlainInit(localDir, false)
	if err != nil {
		return nil, fmt.Errorf("failed to initialize git repository: %w", err)
	}

	// Write files to repository
	if err := m.writeFiles(localDir, files); err != nil {
		return nil, fmt.Errorf("failed to write files: %w", err)
	}

	// Add files to git
	worktree, err := repo.Worktree()
	if err != nil {
		return nil, fmt.Errorf("failed to get worktree: %w", err)
	}

	if err := worktree.AddGlob("."); err != nil {
		return nil, fmt.Errorf("failed to add files to git: %w", err)
	}

	// Commit files
	commitHash, err := worktree.Commit("Initial commit - Generated by Forge Engine", &git.CommitOptions{
		Author: &object.Signature{
			Name:  "Forge Engine",
			Email: "forge@example.com",
			When:  time.Now(),
		},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to commit files: %w", err)
	}

	gitLogger.Info("Files committed", zap.String("commit_hash", commitHash.String()))

	// Skip remote operations - only keep local repository
	gitLogger.Info("Repository created locally", zap.String("local_path", localDir))

	return &Repository{
		URL:      fmt.Sprintf("file://%s", localDir), // Use local file URL
		LocalDir: localDir,
		repo:     repo,
	}, nil
}

func (m *Manager) writeFiles(baseDir string, files map[string]string) error {
	for filePath, content := range files {
		fullPath := filepath.Join(baseDir, filePath)
		
		// Create directory if needed
		dir := filepath.Dir(fullPath)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", dir, err)
		}

		// Write file
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			return fmt.Errorf("failed to write file %s: %w", fullPath, err)
		}
	}

	// Create a basic README if not present
	readmePath := filepath.Join(baseDir, "README.md")
	if _, err := os.Stat(readmePath); os.IsNotExist(err) {
		readme := `# Generated Application

This application was generated by Forge Engine.

## Getting Started

1. Install dependencies
2. Run the application
3. Access the application at the provided URL

## Generated Files

This repository contains all the generated code and configuration files.
`
		if err := os.WriteFile(readmePath, []byte(readme), 0644); err != nil {
			return fmt.Errorf("failed to write README: %w", err)
		}
	}

	return nil
}

func (m *Manager) sanitizeRepoName(appName string) string {
	// Convert to lowercase and replace invalid characters
	name := strings.ToLower(appName)
	name = strings.ReplaceAll(name, " ", "-")
	name = strings.ReplaceAll(name, "_", "-")
	
	// Remove invalid characters
	var result strings.Builder
	for _, r := range name {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			result.WriteRune(r)
		}
	}
	
	name = result.String()
	
	// Ensure it doesn't start or end with dash
	name = strings.Trim(name, "-")
	
	// Ensure minimum length
	if len(name) < 3 {
		name = fmt.Sprintf("app-%s", name)
	}
	
	// Add timestamp to ensure uniqueness
	timestamp := time.Now().Format("20060102-150405")
	return fmt.Sprintf("%s-%s", name, timestamp)
}

func (m *Manager) CleanupRepository(repo *Repository) error {
	if repo == nil || repo.LocalDir == "" {
		return nil
	}

	if err := os.RemoveAll(repo.LocalDir); err != nil {
		return fmt.Errorf("failed to cleanup repository directory %s: %w", repo.LocalDir, err)
	}

	logger.Logger.Info("Repository cleaned up", zap.String("local_dir", repo.LocalDir))
	return nil
}

// ValidateGitConfig checks if git configuration is valid
func (m *Manager) ValidateGitConfig() error {
	if m.config.BaseURL == "" {
		return fmt.Errorf("git base URL is required")
	}
	if m.config.Token == "" {
		return fmt.Errorf("git token is required")
	}
	if m.config.Username == "" {
		return fmt.Errorf("git username is required")
	}
	if m.config.Organization == "" {
		return fmt.Errorf("git organization is required")
	}
	return nil
}

// CreateGitHubRepository creates a new GitHub repository using GitHub API
func (m *Manager) CreateGitHubRepository(ctx context.Context, repoName string, private bool) (string, error) {
	gitLogger := logger.Logger.With(zap.String("component", "git_manager"), zap.String("repo_name", repoName))
	
	// Validate required configuration
	if m.config.Token == "" {
		return "", fmt.Errorf("GitHub token is required for creating repositories. Please set git.token in config")
	}
	if m.config.Username == "" && m.config.Organization == "" {
		return "", fmt.Errorf("GitHub username or organization is required. Please set git.username or git.organization in config")
	}
	
	// Determine owner (organization or username)
	owner := m.config.Organization
	if owner == "" {
		owner = m.config.Username
	}
	
	if owner == "" {
		return "", fmt.Errorf("cannot determine repository owner: both username and organization are empty")
	}
	
	repoURL := fmt.Sprintf("https://github.com/%s/%s", owner, repoName)
	
	// Check if repository already exists by trying to get it
	req, err := http.NewRequestWithContext(ctx, "GET", 
		fmt.Sprintf("https://api.github.com/repos/%s/%s", owner, repoName), nil)
	if err != nil {
		return "", fmt.Errorf("failed to create request: %w", err)
	}
	
	req.SetBasicAuth(m.config.Username, m.config.Token)
	req.Header.Set("Accept", "application/vnd.github.v3+json")
	
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err == nil {
		resp.Body.Close()
		if resp.StatusCode == 200 {
			gitLogger.Info("Repository already exists", zap.String("repo_url", repoURL))
			return repoURL, nil
		}
	}
	
	// Create repository
	createReq := map[string]interface{}{
		"name":    repoName,
		"private": private,
	}
	
	reqBody, err := json.Marshal(createReq)
	if err != nil {
		return "", fmt.Errorf("failed to marshal request: %w", err)
	}
	
	req, err = http.NewRequestWithContext(ctx, "POST", 
		fmt.Sprintf("https://api.github.com/orgs/%s/repos", owner), 
		strings.NewReader(string(reqBody)))
	if err != nil {
		// Try user endpoint if org endpoint fails
		req, err = http.NewRequestWithContext(ctx, "POST", 
			"https://api.github.com/user/repos", 
			strings.NewReader(string(reqBody)))
		if err != nil {
			return "", fmt.Errorf("failed to create request: %w", err)
		}
	}
	
	req.SetBasicAuth(m.config.Username, m.config.Token)
	req.Header.Set("Accept", "application/vnd.github.v3+json")
	req.Header.Set("Content-Type", "application/json")
	
	resp, err = client.Do(req)
	if err != nil {
		return "", fmt.Errorf("failed to create repository: %w", err)
	}
	defer resp.Body.Close()
	
	if resp.StatusCode != 201 && resp.StatusCode != 200 {
		body, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("failed to create repository: status %d, body: %s", resp.StatusCode, string(body))
	}
	
	gitLogger.Info("GitHub repository created", zap.String("repo_url", repoURL))
	return repoURL, nil
}

// CloneBranch clones a specific branch from a GitHub repository
func (m *Manager) CloneBranch(ctx context.Context, repoURL string, branchName string, localDir string) error {
	gitLogger := logger.Logger.With(zap.String("component", "git_manager"), 
		zap.String("repo_url", repoURL), zap.String("branch", branchName))
	
	// Remove existing directory if it exists
	if err := os.RemoveAll(localDir); err != nil {
		return fmt.Errorf("failed to clean local directory: %w", err)
	}
	
	if err := os.MkdirAll(localDir, 0755); err != nil {
		return fmt.Errorf("failed to create local directory: %w", err)
	}
	
	gitLogger.Info("Cloning branch", zap.String("branch", branchName))
	
	// Clone repository with specific branch
	repo, err := git.PlainCloneContext(ctx, localDir, false, &git.CloneOptions{
		URL:           repoURL,
		ReferenceName: plumbing.NewBranchReferenceName(branchName),
		SingleBranch:  true,
		Auth:          m.auth,
		Progress:      os.Stdout,
	})
	
	if err != nil {
		// Try cloning main/master branch and then checkout
		repo, err = git.PlainCloneContext(ctx, localDir, false, &git.CloneOptions{
			URL:      repoURL,
			Auth:     m.auth,
			Progress: os.Stdout,
		})
		if err != nil {
			return fmt.Errorf("failed to clone repository: %w", err)
		}
		
		// Checkout the branch
		worktree, err := repo.Worktree()
		if err != nil {
			return fmt.Errorf("failed to get worktree: %w", err)
		}
		
		err = worktree.Checkout(&git.CheckoutOptions{
			Branch: plumbing.NewBranchReferenceName(branchName),
		})
		if err != nil {
			return fmt.Errorf("failed to checkout branch %s: %w", branchName, err)
		}
	}
	
	gitLogger.Info("Branch cloned successfully", zap.String("local_dir", localDir))
	return nil
}

// GetBranchFiles extracts all files from a cloned repository branch
func (m *Manager) GetBranchFiles(localDir string) (map[string]string, error) {
	files := make(map[string]string)
	
	err := filepath.Walk(localDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		
		// Skip directories and hidden files
		if info.IsDir() || strings.HasPrefix(info.Name(), ".") {
			return nil
		}
		
		// Skip .git directory
		if strings.Contains(path, ".git") {
			return nil
		}
		
		// Read file content
		content, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("failed to read file %s: %w", path, err)
		}
		
		// Use relative path as key
		relPath, err := filepath.Rel(localDir, path)
		if err != nil {
			return fmt.Errorf("failed to get relative path for %s: %w", path, err)
		}
		
		files[relPath] = string(content)
		return nil
	})
	
	if err != nil {
		return nil, fmt.Errorf("failed to walk directory: %w", err)
	}
	
	return files, nil
}
